# Generated by Django 3.1.2 on 2020-11-09 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CTPS', models.FloatField(blank=True, max_length=11, null=True)),
                ('salario', models.FloatField(blank=True, max_length=5, null=True)),
                ('Admissao', models.DateField(blank=True, null=True)),
                ('CPF', models.FloatField(blank=True, max_length=11, null=True)),
                ('Cargo', models.CharField(choices=[['T', 'Técnico'], ['V', 'Vendedor'], ['G', 'Gerente']], max_length=1, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.pessoa')),
            ],
        ),
    ]
