# Generated by Django 3.1.2 on 2020-11-09 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='Admissao',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='CPF',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='CTPS',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
