# Generated by Django 3.1.2 on 2020-11-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20201108_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('sobrenome', models.CharField(max_length=100, null=True)),
                ('nascimento', models.DateField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('CNPJ', models.CharField(max_length=14, null=True)),
                ('telefone', models.CharField(max_length=12, null=True)),
                ('endereco', models.CharField(max_length=264, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Admissao',
            new_name='admissao',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='Cargo',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='perfil',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='nascimento',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
