# Generated by Django 3.1.3 on 2020-11-16 02:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20201113_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('telefone', models.CharField(max_length=12, null=True)),
                ('endereco', models.CharField(max_length=150, null=True)),
                ('CNPJ', models.CharField(max_length=14, null=True)),
                ('categoria', models.CharField(choices=[['CFTV', 'CFTV'], ['AL', 'Alarme'], ['CA', 'Controle de Acesso'], ['TE', 'Telefonia'], ['RE', 'Redes'], ['PE', 'Portão Eletrônico']], max_length=6, null=True)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='funcionario',
            managers=[
            ],
        ),
    ]
