# Generated by Django 3.1.3 on 2020-11-28 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_produto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='nomep',
        ),
    ]
