# Generated by Django 3.1.3 on 2020-11-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_produto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CNPJ',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='CNPJ',
            field=models.CharField(max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='CPF',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
