# Generated by Django 3.1.3 on 2020-11-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_comment_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='categoria',
            field=models.CharField(choices=[['CFTV', 'CFTV'], ['AL', 'Alarme'], ['CA', 'Controle de Acesso'], ['TE', 'Telefonia'], ['RE', 'Redes'], ['PE', 'Portão Eletrônico']], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='comissao',
            field=models.CharField(choices=[['5%', '5%'], ['10%', '10%'], ['15%', '15%']], max_length=6, null=True),
        ),
    ]
