# Generated by Django 3.1.3 on 2020-11-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_auto_20201130_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.cliente'),
        ),
        migrations.AddField(
            model_name='event',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.funcionario'),
        ),
    ]
