# Generated by Django 3.1.3 on 2020-12-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20201130_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date', '-priority', 'event', 'cliente', 'funcionario')},
        ),
        migrations.AlterField(
            model_name='event',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app1.cliente'),
        ),
        migrations.AlterField(
            model_name='event',
            name='funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='app1.funcionario'),
        ),
    ]
