# Generated by Django 3.1.3 on 2020-12-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20201201_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.cliente'),
        ),
    ]
