# Generated by Django 3.1.3 on 2020-12-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_produto_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cliente',
        ),
    ]
