# Generated by Django 3.1.3 on 2020-12-03 00:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_auto_20201202_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.cliente')),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='compra',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-date', '-priority', 'event')},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='event',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.event'),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.produto'),
        ),
    ]
