# Generated by Django 3.1.3 on 2020-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20201202_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.AddField(
            model_name='comment',
            name='cargo',
            field=models.CharField(choices=[['T', 'Técnico'], ['V', 'Vendedor'], ['G', 'Gerente']], max_length=1, null=True),
        ),
    ]
