# Generated by Django 3.1.3 on 2020-12-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_auto_20201203_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cargo',
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
