# Generated by Django 3.1.3 on 2020-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20201203_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='produto',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='produto',
            field=models.ManyToManyField(to='app1.Produto'),
        ),
    ]
