# Generated by Django 3.1.3 on 2020-12-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_auto_20201203_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='event',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='categoria',
            field=models.CharField(choices=[['CFTV', 'CFTV'], ['AL', 'Alarme'], ['CA', 'Controle de Acesso'], ['TE', 'Telefonia'], ['RE', 'Redes'], ['PE', 'Portão Eletrônico']], max_length=6, null=True),
        ),
    ]
