# Generated by Django 3.1.3 on 2020-12-04 14:23

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_auto_20201203_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.CharField(choices=[['Jan', 'Janeiro'], ['Fev', 'Fevereiro'], ['Mar', 'Março'], ['Abr', 'Abril'], ['Mai', 'Maio'], ['Jun', 'Junho'], ['Jul', 'Julho'], ['Ago', 'Agosto'], ['Set', 'Setembro'], ['Out', 'Outrubro'], ['Nov', 'Novembro'], ['Dez', 'Dezembro']], max_length=10, null=True)),
                ('meta', models.CharField(max_length=150, null=True)),
                ('data', models.DateField(auto_now=True, null=True)),
                ('cargo', models.CharField(choices=[['V', 'Vendedor'], ['T', 'Técnico']], max_length=1, null=True)),
                ('concluida', models.CharField(choices=[['S', 'Sim'], ['N', 'Não']], max_length=1, null=True)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
