# Generated by Django 3.1.3 on 2020-12-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_metas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='cargo',
            field=models.CharField(choices=[['Vendedor', 'Vendedor'], ['Técnico', 'Técnico']], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='metas',
            name='concluida',
            field=models.CharField(choices=[['Sim', 'Sim'], ['Não', 'Não']], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='metas',
            name='meses',
            field=models.CharField(choices=[['Janeiro', 'Janeiro'], ['Fevereiro', 'Fevereiro'], ['Março', 'Março'], ['Abril', 'Abril'], ['Maio', 'Maio'], ['Junho', 'Junho'], ['Julho', 'Julho'], ['Agosto', 'Agosto'], ['Setembro', 'Setembro'], ['Outubro', 'Outrubro'], ['Novembro', 'Novembro'], ['Dezembro', 'Dezembro']], max_length=10, null=True),
        ),
    ]
