# Generated by Django 3.1.3 on 2020-12-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20201204_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metas',
            name='data',
            field=models.DateField(null=True),
        ),
    ]
