# Generated by Django 3.1.3 on 2020-12-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_auto_20201204_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='comissao',
        ),
    ]
